version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: abroad_crm_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abroad_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: abroad_crm_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/abroad_crm?schema=public
    command: >
      sh -c "
      npx prisma migrate deploy &&
      node dist/src/main.js
      "

volumes:
  postgres_data:
